export { EvolutionClient } from './evolution-client.js';
export type { EvolutionClientConfig } from './evolution-client.js';
export { ConnectionWatchdog } from './connection-watchdog.js';
export type { ConnectionState } from './connection-watchdog.js';
export { registerEvolutionWebhookRoute, processInboundText } from './webhook-route.js';
export type { WebhookRouteDeps, ProcessInboundDeps, UnmatchedTextHandler } from './webhook-route.js';
export { recoverPendingMessages } from './pending-recovery.js';
export type { RecoverPendingMessagesDeps } from './pending-recovery.js';
export { evolutionWebhookSchema } from './webhook-schema.js';
export type { EvolutionWebhookPayload, MessagesUpsertEvent, ConnectionUpdateEvent } from './webhook-schema.js';
export { normalizeIncomingMessage, isEchoOfOwnMessage } from './normalize.js';
export { isFromOwner, normalizeJid } from './owner-filter.js';
export { provisionEvolutionWebhook } from './webhook-provisioner.js';
export type { WebhookProvisionerConfig, WebhookProvisionerOptions } from './webhook-provisioner.js';
